---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs00
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: "/mnt/PV00"
    server: kubem04
  persistentVolumeReclaimPolicy: Recycle
