---
apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    run: vote
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30050
  selector:
    run: vote
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      run: vote
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: vote
    spec:
      containers:
      - image: docker.io/kalise/flask-vote-app:latest
        name: vote
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
