---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-share-00
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      name: "share00"
