---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share02
  labels:
    name: share02
spec:
  capacity:
    storage: 1Gi
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  nfs:
    path: "/mnt/share-02"
    server: fileserver
  persistentVolumeReclaimPolicy: Recycle
